title: "winclassic.github.io"
email: ""
description: ""
baseurl: ""
url: "https://winclassic.github.io"
plugins: []

page_excerpts: true
excerpt_separator: <!--more-->

sass:
  style: compressed

exclude:
  - ".vs"